version: '3'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DATABASE: ${DB_DATABASE}
      ENVIROMENT: ${ENVIROMENT}

    command: npm start --env=dev